const {model,Schema} = require('mongoose')

const productSchema = new Schema({
    productName:{
        type:String,
        required:true
    },
    categoryId:{
        type:Schema.Types.ObjectId,
        ref:'Category',
        required:true
    },
    productType:{
        type:String,
        required:true
    },
    header:{
     type:String,
     required:true
    },
    link:{
        text:String,
        url:String
    },
    description:{
        type:String,
        required:true
    },
    images:[
        {
            url:String,
            name:String
        }
    ],
    additionalDetails:{
        gender:String,
        seller:String,
        quantity:String,
        sizes:[{
            size:String
        }],
        address:String,
        services:String
    },
    prices:{
     initialPrice:String,
     discount:String
    },
    reviews:[
        {
            customerName:String,
            review:String
        }
    ],
    userId:{
        type:Schema.Types.ObjectId,
        required:true,
        ref:'User'
    }
})
module.exports = model('Product',productSchema)